// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace lab2.Models;

[Table("Course")]
public partial class Course
{
    [Key]
    [JsonIgnore]

    public int Crs_Id { get; set; }
    [JsonIgnore]

    [StringLength(50)]

    public string Crs_Name { get; set; }
    [JsonIgnore]

    public int? Crs_Duration { get; set; }
    [JsonIgnore]

    public int? Top_Id { get; set; }
    [JsonIgnore]

    [InverseProperty("Crs")]
    public virtual ICollection<Ins_Course> Ins_Courses { get; set; } = new List<Ins_Course>();
    [JsonIgnore]

    [InverseProperty("Crs")]
    public virtual ICollection<Stud_Course> Stud_Courses { get; set; } = new List<Stud_Course>();
    [JsonIgnore]

    [ForeignKey("Top_Id")]
    [InverseProperty("Courses")]
    public virtual Topic Top { get; set; }
}